version: '3.8'
services:
  repo-gui:
    image: ghcr.io/wirepact/contract-gui:1.1.12
    environment:
      - PORT=8080
      - REPO_HOST=http://repo-api:8081
      - REPO_API_KEY=foobar
    ports:
      - 8080:8080
    links:
      - repo-api
      - pki_a
      - pki_b

  repo-api:
    image: ghcr.io/wirepact/contract-api:1.1.12
    environment:
      - DEBUG=true
      - PORT=8081
      - API_KEY=foobar
    ports:
      - 8081:8081

  pki_a:
    image: ghcr.io/wirepact/k8s-pki:2.4.188
    environment:
      - DEBUG=true
      - PORT=8082
      - LOCAL=true
      - API_KEY=pki
    ports:
      - 8082:8082

  pki_b:
    image: ghcr.io/wirepact/k8s-pki:2.4.188
    environment:
      - DEBUG=true
      - PORT=8083
      - LOCAL=true
    ports:
      - 8083:8083
